services:
    mysql:
        image: mysql:latest
        ports:
            - "23306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=root12345

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8100:80"
        environment:
            - PMA_HOST=mysql
            - PMA_ARBITRARY=1
